# Generated by Django 4.2 on 2023-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_email_verified', models.BooleanField(blank=True, default=False, verbose_name='Email Verified?')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Phone Number')),
                ('is_phone_number_verified', models.BooleanField(blank=True, default=False, verbose_name='Phone Number Verified?')),
                ('user_type', models.CharField(choices=[('SUPERADMIN', 'SUPERADMIN'), ('USER', 'USER')], default='USER', max_length=20, verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
